### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by RedRiverCN** [zuihou/zuihou-admin-ui#1]
![7$G6J4A44SW6 JI4IZX__0](https://user-images.githubusercontent.com/22110655/71795864-2a7e7100-3083-11ea-9cb5-56d03a1ebf51.png)
![U5}PUN_QT`)6E@{0X6ZR(GV](https://user-images.githubusercontent.com/22110655/71795865-2b170780-3083-11ea-893a-76b02a7233ad.png)

**Comment by zuihou** [comment]
https://www.kancloud.cn/zuihou/zuihou-admin-cloud/1286227
